"""testing with association table instead of table object

Revision ID: 4a110c7dce56
Revises: 6ba5b599b830
Create Date: 2023-08-21 22:39:08.028444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a110c7dce56'
down_revision = '6ba5b599b830'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
