"""added password attr to User for real this time

Revision ID: 7cabf052e032
Revises: 2d253d2ad68d
Create Date: 2023-08-24 05:51:27.234700

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cabf052e032'
down_revision: Union[str, None] = '2d253d2ad68d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'password')
    op.add_column('users', sa.Column('password', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    op.add_column('games', sa.Column('password', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
